### ISSUE TITLE
Defining repository package inclusion scope

### ISSUE THREAD

**Issue by dgkf** [pharmaR/regulatory-r-repo-wg#18]
Migrating cards from our meeting discussion

> Definition of what R packages are in scope and out of scope for a quality assessment

**Comment by kkmann** [comment]
I would keep it very wide. We can limit the amount of submission by being relatively strict on the inclusion critera. Wouldn't go via application area etc, but only via quality.

**Comment by kkmann** [comment]
duplicate with #34
