### ISSUE TITLE
branch protection / workflow

### ISSUE THREAD

**Issue by kkmann** [pharmaR/regulatory-r-repo-wg#27]
@dgkf  Would suggest to implement a branch protection rule for main (changes only via PR, 1+ reviewer) to keep things tidy. Make squash ff default?

**Comment by yannfeat** [comment]
> @dgkf Would suggest to implement a branch protection rule for main (changes only via PR, 1+ reviewer) to keep things tidy. Make squash ff default?

Shouldn't we set an example for future validated packages and avoid using squash commits? I think that squash commits could be considered bad coding practices for validated environments in the future, as they decrease transparency.

**Comment by kkmann** [comment]
@yannfeat this is really just for our repo here, in terms of recommendations for developing statistical software (R apckages) I would recommend heading over to https://rconsortium.github.io/asa-biop-swe-wg/join_us.html :)

**Comment by kkmann** [comment]
done.
