### ISSUE TITLE
Project Support team meeting (2023-01-12)

### ISSUE THREAD

**Issue by Crosita** [pharmaR/regulatory-r-repo-wg#30]
Agenda: 
- [x] Review the GH discussion about our Vision for this year's pilot #26
  - [x] further refinement required? Yes, move discussion to new gdrive (ask @Crosita to get access)
- [x] ~~Define next steps for sub teams, e.g.~~ not discussed
  - [x] ~~list needs of our stakeholders~~
  - [x] ~~create mock ups/wireframe~~
  - [x] ~~get feedback from stakeholders on mock up/wireframe~~

**Comment by kkmann** [comment]
@borgmaan @Crosita @dgkf let's try and concretize this a bit further over the next days.

- [ ] look into house-keeping issues
  - [ ] #27 
  - [ ] #20 
- [ ] update on #15 (esp. how to approach reg aspect)
- [ ] discuss scope: industry agnostic vs open to all but focussed on pharma needs

**Comment by dgkf** [comment]
Maybe you've already seen, but I also sent a request to get added to a Submissions Working Group meeting just to start building that network. 

Regardless of what we decide as next steps, I think that will be a fruitful partnership.

**Comment by kkmann** [comment]
@Crosita @yannfeat would be interested in joining tomorrow as well

**Comment by Crosita** [comment]
**2023-01-26 meeting**

- Finalize Vision
- Finalize Stakeholders and their needs
- Define next steps: suggestion is to assign a project support individual per "stakeholder" responsible for driving the work for that stakeholder. Eg: pulling the tech saavy members that you need, build a little squad, develop mock ups and install a way of communicating and receiving feedback from your stakeholder.
- Closing: suggestion to add a Validation Lead + create central material to introduce our WG to stakeholders

**Next meeting**

- Review Introduction slide deck
- Assign stakeholder per project support team member
- Introduce Val Lead (Stefan from BI?)

**Comment by Crosita** [comment]
**2023-02-02 meeting**

- Review Introduction slide deck
- Assign stakeholder per project support team member
- Introduce Val Lead, Stefan from BI
- Closing: Project yourself interviewing your stakeholder group and build the material in Introduction slide deck you feel will be needed

**Next meeting**
- Review Introduction slide deck

**Comment by borgmaan** [comment]
## 2023-04-13 Meeting

**Topics:** 
- Next steps/ways of working with all WG members (@kkmann)
    - Needs: 
        - Proposal for next steps 
        - Project support team alignment on approach 
        - Slide to show this in the All Hands. 
- Finish interviews and conclude on expectations from each stakeholder group (all). 
- [Reg R / Posit April 12th recap](https://github.com/pharmaR/regulatory-r-repo-wg/issues/47) (@dgkf )
- [HA Inspector](https://github.com/pharmaR/regulatory-r-repo-wg/issues/48) (@dgkf )
- Upcoming events people should attend and get ready for:
    - All Hands April 27th

**Comment by borgmaan** [comment]
## 2023-04-13 Meeting Minutes

### Attendees:
Doug Kelkoff
Paul Schuette
Kevin Kunzmann
Yann Feat
Andrew Borgman

### Notes:
- Next steps/ways of working with all WG members
    - Propose to engage broader WG in next steps of solution design based on interest
    - Following design, support team will engage in 2nd round of stakeholder interviews for feedback on result of more tangible solution proposals
    - @dgkf to draft slide(s) for All Hands call on 4/27 to outline proposal for next steps and communicate ask for support/participation in design process for broader WG members
- Posit call recap
    - Suggestion to engage in discussion with additional vendors around commercial solutions in this space
    - @dgkf to connect with Atorus given their recent OpenVal offering
