### ISSUE TITLE
Early knowledge-gathering deliverables

### ISSUE THREAD

**Issue by dgkf** [pharmaR/regulatory-r-repo-wg#33]
### Discussed in https://github.com/pharmaR/regulatory-r-repo-wg/discussions/5

Migrated following decision in #20

<div type='discussions-op-text'>

<sup>Originally posted by **dgkf** November 16, 2022</sup>
Before we get too far down the road of building any sort of repository infrastructure, let's make sure that what we're building is what is needed. 

Even if our respective organizations have opinions about what is needed, ultimately these processes are only as valuable as a regulating authority's stance on the approach. To make sure that we're delivering what they need, let's engage them early.

I propose that we build our regulatory technical requirements in three stages:

1. Start with a bulleted list of features - let's get regulatory authority feedback on how critical each is to building confidence in shared software. We can assume our baseline is simply using CRAN.
2. Assuming there is some ambiguity in their response, I think a useful next step would be to wireframe what a service could look like. Hopefully this makes the service a bit more concrete to the point that we could get more direct feedback.
3. With a better idea of what the needs are, we could start thinking about what architecture gets us there.

I'm curious to hear what other initial deliverables we feel we need to start us off on the right path.</div>

**Comment by kkmann** [comment]
@dgkf can we close this or split it up in actionable issues? I think we already have quite a few issues related to this, right? e.g. #23

**Comment by dgkf** [comment]
Sounds good to me - this was just a direct migration of the discussion for transparency.

Let's close it out. I think we have all the tasks covered in other issues and if not we can open more focused ones.
