### ISSUE TITLE
Take-aways from FDA draft guidance "Computer Software Assurance for Production and Quality System Software"

### ISSUE THREAD

**Issue by dgkf** [pharmaR/regulatory-r-repo-wg#35]
### Discussed in https://github.com/pharmaR/regulatory-r-repo-wg/discussions/12

Migrated following decision in #20

---

<div type='discussions-op-text'>

<sup>Originally posted by **dgkf** November 29, 2022</sup>
This new guidance is a follow-up to the 20-year-old "General Principles of Software Validation" that is still often used as the basis for many decisions regarding software systems.

I encourage everyone to read through - both to provide feedback and to understand a health authority's perspective on requirements of any software system. If you have any key takeaways, please kick off a thread and we can hash out the impact. If we want to spur any proposals from it we can carry on the discussion in a designated thread.

[Computer Software Assurance for Production and Quality System Software [Draft]](https://www.fda.gov/regulatory-information/search-fda-guidance-documents/computer-software-assurance-production-and-quality-system-software)

This covers primarily medical devices, but might be interesting to comb through to tease out any indications one what we might expect for analysis regarding submissions.
</div>

> <div type='discussions-op-text'>
> 
> <sup>Originally posted by @kkmann in https://github.com/pharmaR/regulatory-r-repo-wg/discussions/12#discussioncomment-4273138</sup>
>  In case someone missed it - I also found this very helpful: https://youtu.be/dtdd_jc1ybw </div>

> <div type='discussions-op-text'>
> 
> <sup>Originally posted by @kkmann in https://github.com/pharmaR/regulatory-r-repo-wg/discussions/12#discussioncomment-4275755</sup>
>  Hm, not so sure how applicable this is. I like the explicit mentioning of a difference between initial validation and maintaining a validated state. Could mean that initial peer review + automated change control triggering re-reviews might be viable. One could rely on software versioning to detect major changes (pragmatic but maybe not enough) or inspect changes in package namespaces. </div>

**Comment by kkmann** [comment]
transferred to 'references' in gdrive folder
