### ISSUE TITLE
Where should discussion happen?

### ISSUE THREAD

**Issue by dgkf** [pharmaR/regulatory-r-repo-wg#37]
### Discussed in https://github.com/pharmaR/regulatory-r-repo-wg/discussions/10

Migrated from discussion in #20

---

<div type='discussions-op-text'>

<sup>Originally posted by **dgkf** November 17, 2022</sup>
Of course we have the discussion boards here, but I wanted to open up the floor for other suggestions. </div>

> <div type='discussions-op-text'>
> 
> <sup>Originally posted by @pedrobtz in https://github.com/pharmaR/regulatory-r-repo-wg/discussions/10#discussioncomment-4171846</sup>
> Of course we have the discussion boards here, but I wanted to open up the floor for other suggestions. </div>
> 
> > <div type='discussions-op-text'>
> > 
> > <sup>Originally posted by @dgkf in https://github.com/pharmaR/regulatory-r-repo-wg/discussions/10#discussioncomment-4382532</sup>
> > The R Validation Hub has the workspace `rvalidationhub.slack.com`. In fact we have a mostly-stale channel for "infrastructure" that might suit this nicely. </div>

> <div type='discussions-op-text'>
> 
> <sup>Originally posted by @kkmann in https://github.com/pharmaR/regulatory-r-repo-wg/discussions/10#discussioncomment-4273124</sup>
> I am kind of in favor of keeping it here - why start a second platform? Everything in one place, nice and tidy :) No strong feelings though </div>

> <div type='discussions-op-text'>
> 
> <sup>Originally posted by @Xyarz in https://github.com/pharmaR/regulatory-r-repo-wg/discussions/10#discussioncomment-4324284</sup>
>I have no strong feelings here as well. The benefit of a Slack channel that I could see, is the cross-project communication as there is a Slack for the RValidationHub out there already - where all projects have their seperate channels too. </div>

**Comment by kkmann** [comment]
we agreed on GH issues + gdrive comments for now, closing.
