### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by dgkf** [pharmaR/regulatory-r-repo-wg#39]
Suggested at our #30 meeting, we thought it might be a good idea to move some of the more public facing content into a website. 

`quarto` was thrown out as an option, which I also think would be a best fit for an R-based website.

Initially, just having our vision statement somewhere more accessible and presentable would be a good start and we can add content as we go from there.

**Comment by kkmann** [comment]
Tagging @Xyarz and @yannfeat in case one of them would like to grab this. 

I would point to https://github.com/RConsortium/asa-biop-swe-wg as an example for how to set this up on GH.

Quarto makes this a breeze, takes some fiddling with GH actions until it's set up but this is also a great learning opportunity in case someone wants to know how this whole CI/CD stuff works.

If you are interested, just self-assign to the issue and start a pull request. Once the website is there, we probably need a few iterations with @dgkf until the CI/CD stuff works.

**Comment by yannfeat** [comment]
#41 I tried but it doesn't work for me. If some could help me, I would be grateful.
